### ISSUE TITLE
Mismatch `author` between `<mgem-list>/mruby-stringio.gem` and `<mruby-stringio>/mrbgem.rake`

### ISSUE THREAD

**Issue by dearblue** [ksss/mruby-stringio#10]
正しいのは次のうちのどちらかになるのではないでしょうか？

  - https://github.com/mruby/mgem-list/blob/ef95275de1a6b55ee6099e16421e8bc3d2d0ee52/mruby-stringio.gem#L3

    > ```yaml
    > author: ksss
    > ```

  - https://github.com/ksss/mruby-stringio/blob/97cc4434519e85a0785a1b4cf6f872a220f772db/mrbgem.rake#L3

    > ```yaml
    >   spec.author  = 'mruby developers'
    > ```

**Comment by ksss** [comment]
ご報告ありがとうございます。確かに大きな違いがありますね。
特に支障がなければ、他のライブラリーと合わせてmrbgem.rakeを以下のようにしようと思います。

`spec.author = 'ksss <co000ri@gmail.com>'`

**Comment by dearblue** [comment]
もともと mruby-stringio は @ksss さんが始められたプロジェクトだと思うので、問題ないと思います。

:smiley_cat: あと余計なことではありますが、`LICENSE` ファイルが用意されると、https://github.com/dearblue/mruby-license で自動回収されるようになって僕が喜びます。
