### ISSUE TITLE
Fails builds on Windows by too old ruby

### ISSUE THREAD

**Issue by unasuke** [ksss/mruby-stringio#4]
Build in Windows on appveyor is failing at master branch. (also travis, But it's succeeded at forked repository without any changes.)
https://ci.appveyor.com/project/ksss/mruby-stringio/branch/master

It fails because of using ruby 1.9.3 that  doesn't support TLS v1.
I tried to set env `%ruby_version%` to 25, build has succeeded.
https://ci.appveyor.com/project/unasuke/mruby-stringio

![screenshot from 2018-12-30 17-05-08](https://user-images.githubusercontent.com/4487291/50545368-1b393c00-0c55-11e9-9fce-36e7ab566ba1.png)

Can you set `%ruby_version%` to 25?

**Comment by ksss** [comment]
Passed on appveyor, Grazie!
